from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DTWindow(object):
    def setupUi(self, DT):
        DT.setObjectName("DT")
        DT.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(DT)
        self.centralwidget.setObjectName("centralwidget")

        self.processEntrenoTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.processEntrenoTextEdit.setGeometry(QtCore.QRect(550, 140, 600, 300))
        self.processEntrenoTextEdit.setObjectName("processEntrenoTextEdit")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(500, 60, 20, 600))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        
        self.trainValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.trainValueLabel.setGeometry(QtCore.QRect(110, 220, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trainValueLabel.setFont(font)
        self.trainValueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trainValueLabel.setObjectName("trainValueLabel")

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(40, 130, 400, 30))  
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")

        self.setSizePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.setSizePushButton.setGeometry(QtCore.QRect(190, 170, 100, 30))  
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setSizePushButton.setFont(font)
        self.setSizePushButton.setObjectName("setSizePushButton")

        self.testValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.testValueLabel.setGeometry(QtCore.QRect(260, 220, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testValueLabel.setFont(font)
        self.testValueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.testValueLabel.setObjectName("testValueLabel")

        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(200, 220, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")

        self.criterio_label5 = QtWidgets.QLabel(self.centralwidget)
        self.criterio_label5.setGeometry(QtCore.QRect(40, 270, 900, 30)) 
        font = QtGui.QFont()
        font.setPointSize(10)
        self.criterio_label5.setFont(font)
        self.criterio_label5.setObjectName("criterio_label5")

        self.criterioComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.criterioComboBox.setGeometry(QtCore.QRect(240, 270, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.criterioComboBox.setFont(font)
        self.criterioComboBox.setObjectName("criterioComboBox")
        self.criterioComboBox.addItem("")
        self.criterioComboBox.addItem("")
        self.criterioComboBox.addItem("")

        self.splitter_label_6 = QtWidgets.QLabel(self.centralwidget)
        self.splitter_label_6.setGeometry(QtCore.QRect(40, 320, 900, 30)) #(x, y, ancho, alto)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.splitter_label_6.setFont(font)
        self.splitter_label_6.setObjectName("splitter_label_6")

        self.splitterComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.splitterComboBox.setGeometry(QtCore.QRect(240, 320, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.splitterComboBox.setFont(font)
        self.splitterComboBox.setObjectName("splitterComboBox")
        self.splitterComboBox.addItem("")
        self.splitterComboBox.addItem("")
##
        self.maxDepth_label_7 = QtWidgets.QLabel(self.centralwidget)
        self.maxDepth_label_7.setGeometry(QtCore.QRect(40, 370, 900, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxDepth_label_7.setFont(font)
        self.maxDepth_label_7.setObjectName("maxDepth_label_7")

        self.maxDepth_label_8_None_1 = QtWidgets.QLabel(self.centralwidget)
        self.maxDepth_label_8_None_1.setGeometry(QtCore.QRect(40, 390, 900, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxDepth_label_8_None_1.setFont(font)
        self.maxDepth_label_8_None_1.setObjectName("maxDepth_label_8_None_1")

        self.maxDepth_label_8_None_2 = QtWidgets.QLabel(self.centralwidget)
        self.maxDepth_label_8_None_2.setGeometry(QtCore.QRect(40, 410, 900, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxDepth_label_8_None_2.setFont(font)
        self.maxDepth_label_8_None_2.setObjectName("maxDepth_label_8_None_2")

        self.maxDepth_label_8_None_3 = QtWidgets.QLabel(self.centralwidget)
        self.maxDepth_label_8_None_3.setGeometry(QtCore.QRect(40, 430, 900, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxDepth_label_8_None_3.setFont(font)
        self.maxDepth_label_8_None_3.setObjectName("maxDepth_label_8_None_3")

        self.maxDepthLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.maxDepthLineEdit.setGeometry(QtCore.QRect(240, 370, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxDepthLineEdit.setFont(font)
        self.maxDepthLineEdit.setObjectName("maxDepthLineEdit")
        
        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(40, 20, 900, 40)) 
        font = QtGui.QFont()
        font.setPointSize(16) 
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")

        self.EntrenarPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.EntrenarPushButton.setGeometry(QtCore.QRect(240, 480, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EntrenarPushButton.setFont(font)
        self.EntrenarPushButton.setObjectName("EntrenarPushButton")

        self.MConfusionPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.MConfusionPushButton.setGeometry(QtCore.QRect(550, 480, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MConfusionPushButton.setFont(font)
        self.MConfusionPushButton.setObjectName("MConfusionPushButton")

        self.descargaPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.descargaPushButton.setGeometry(QtCore.QRect(1000, 480, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.descargaPushButton.setFont(font)
        self.descargaPushButton.setObjectName("descargaPushButton")

        self.sizeConjuntoLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sizeConjuntoLineEdit.setGeometry(QtCore.QRect(80, 170, 100, 30)) 
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sizeConjuntoLineEdit.setFont(font)
        self.sizeConjuntoLineEdit.setObjectName("sizeConjuntoLineEdit")

        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(40, 220, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")

        self.label9 = QtWidgets.QLabel(self.centralwidget)
        self.label9.setGeometry(QtCore.QRect(550, 80, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label9.setFont(font)
        self.label9.setObjectName("label9")

        self.titulo2Label = QtWidgets.QLabel(self.centralwidget)
        self.titulo2Label.setGeometry(QtCore.QRect(40, 80, 900, 30))  
        font = QtGui.QFont()
        font.setPointSize(12)
        self.titulo2Label.setFont(font)
        self.titulo2Label.setObjectName("titulo2Label")

        DT.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DT)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 17))
        self.menubar.setObjectName("menubar")
        DT.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DT)
        self.statusbar.setObjectName("statusbar")
        DT.setStatusBar(self.statusbar)

        self.retranslateUi(DT)
        QtCore.QMetaObject.connectSlotsByName(DT)

    def retranslateUi(self, DT):
        _translate = QtCore.QCoreApplication.translate
        DT.setWindowTitle(_translate("DT", "Configurar Árbol de decisión"))
        self.titulo.setText(_translate("DT", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; text-decoration: underline;\">Árbol de Decisión</span></p></body></html>"))
        self.titulo2Label.setText(_translate("DT", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Configuración</span></p></body></html>"))
        self.label1.setText(_translate("DT", "Tamaño del conjunto de entrenamiento (%):"))
        self.setSizePushButton.setText(_translate("DT", "Set"))
        self.label2.setText(_translate("DT", "Train:"))
        self.label4.setText(_translate("DT", "Test:"))
        self.descargaPushButton.setText(_translate("DT", "Descargar"))
        self.MConfusionPushButton.setText(_translate("DT", "Gráficas"))
        self.EntrenarPushButton.setText(_translate("DT", "Entrenar"))
        self.label9.setText(_translate("NNWindow", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Entrenamiento de modelo</span></p></body></html>"))
        self.splitter_label_6.setText(_translate("DT", "<b>Splitter:</b>"))
        self.criterio_label5.setText(_translate("DT", "<b>Criterio:</b>"))
        self.splitterComboBox.setItemText(0, _translate("DT", "best"))
        self.splitterComboBox.setItemText(1, _translate("DT", "random"))
        self.criterioComboBox.setItemText(0, _translate("DT", "gini"))
        self.criterioComboBox.setItemText(1, _translate("DT", "entropy"))
        self.criterioComboBox.setItemText(2, _translate("DT", "log_loss"))
        self.maxDepth_label_7.setText(_translate("DT", "<b>Profundidad Máxima:</b>"))
        self.maxDepth_label_8_None_1.setText(_translate("DT", "(Deja el campo vacío para"))
        self.maxDepth_label_8_None_2.setText(_translate("DT", "usar la profuncidad"))
        self.maxDepth_label_8_None_3.setText(_translate("DT", "predeterminada (None))"))



        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DT = QtWidgets.QMainWindow()
    ui = Ui_DTWindow()
    ui.setupUi(DT)
    DT.show()
    sys.exit(app.exec_())
