from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KNN(object):
    def setupUi(self, KNN):
        KNN.setObjectName("KNN")
        KNN.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(KNN)
        self.centralwidget.setObjectName("centralwidget")

        self.titulo_2 = QtWidgets.QLabel(self.centralwidget)
        self.titulo_2.setGeometry(QtCore.QRect(40, 20, 900, 40))
        font = QtGui.QFont()
        font.setPointSize(16) 
        self.titulo_2.setFont(font)
        self.titulo_2.setObjectName("titulo_2")

        self.titulo2Label = QtWidgets.QLabel(self.centralwidget)
        self.titulo2Label.setGeometry(QtCore.QRect(40, 80, 900, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.titulo2Label.setFont(font)
        self.titulo2Label.setObjectName("titulo2Label")

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(40, 130, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")

        self.sizeConjuntoLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sizeConjuntoLineEdit.setGeometry(QtCore.QRect(80, 170, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sizeConjuntoLineEdit.setFont(font)
        self.sizeConjuntoLineEdit.setObjectName("sizeConjuntoLineEdit")

        self.setSizePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.setSizePushButton.setGeometry(QtCore.QRect(190, 170, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setSizePushButton.setFont(font)
        self.setSizePushButton.setObjectName("setSizePushButton")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 220, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.trainValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.trainValueLabel.setGeometry(QtCore.QRect(110, 220, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trainValueLabel.setFont(font)
        self.trainValueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trainValueLabel.setObjectName("trainValueLabel")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 220, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.testValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.testValueLabel.setGeometry(QtCore.QRect(260, 220, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testValueLabel.setFont(font)
        self.testValueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.testValueLabel.setObjectName("testValueLabel")

        self.kVecinos_label5 = QtWidgets.QLabel(self.centralwidget)
        self.kVecinos_label5.setGeometry(QtCore.QRect(40, 270, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kVecinos_label5.setFont(font)
        self.kVecinos_label5.setObjectName("kVecinos_label5")

        self.kVecinosLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.kVecinosLineEdit.setGeometry(QtCore.QRect(240, 270, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kVecinosLineEdit.setFont(font)
        self.kVecinosLineEdit.setObjectName("kVecinosLineEdit")

        self.weight_label_6 = QtWidgets.QLabel(self.centralwidget)
        self.weight_label_6.setGeometry(QtCore.QRect(40, 320, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.weight_label_6.setFont(font)
        self.weight_label_6.setObjectName("weight_label_6")

        self.WeightComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.WeightComboBox.setGeometry(QtCore.QRect(240, 320, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WeightComboBox.setFont(font)
        self.WeightComboBox.setObjectName("WeightComboBox")
        self.WeightComboBox.addItem("")
        self.WeightComboBox.addItem("")

        self.algoritmo_label_7 = QtWidgets.QLabel(self.centralwidget)
        self.algoritmo_label_7.setGeometry(QtCore.QRect(40, 370, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.algoritmo_label_7.setFont(font)
        self.algoritmo_label_7.setObjectName("algoritmo_label_7")

        self.algoritmoComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.algoritmoComboBox.setGeometry(QtCore.QRect(240, 370, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.algoritmoComboBox.setFont(font)
        self.algoritmoComboBox.setObjectName("algoritmoComboBox")
        self.algoritmoComboBox.addItem("")
        self.algoritmoComboBox.addItem("")
        self.algoritmoComboBox.addItem("")
        self.algoritmoComboBox.addItem("")

        self.metrica_label_8 = QtWidgets.QLabel(self.centralwidget)
        self.metrica_label_8.setGeometry(QtCore.QRect(40, 420, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.metrica_label_8.setFont(font)
        self.metrica_label_8.setObjectName("metrica_label_8")

        self.p_label_9 = QtWidgets.QLabel(self.centralwidget)
        self.p_label_9.setGeometry(QtCore.QRect(40, 460, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.p_label_9.setFont(font)
        self.p_label_9.setObjectName("p_label_9")

        self.pComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.pComboBox.setGeometry(QtCore.QRect(160, 460, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pComboBox.setFont(font)
        self.pComboBox.setObjectName("pComboBox")
        self.pComboBox.addItem("")
        self.pComboBox.addItem("")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(500, 60, 20, 600))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.EntrenarPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.EntrenarPushButton.setGeometry(QtCore.QRect(240, 510, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EntrenarPushButton.setFont(font)
        self.EntrenarPushButton.setObjectName("EntrenarPushButton")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 80, 400, 30))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setObjectName("label_9")


        self.descargaPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.descargaPushButton.setGeometry(QtCore.QRect(1000, 480, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.descargaPushButton.setFont(font)
        self.descargaPushButton.setObjectName("descargaPushButton")
        
        self.processEntrenoTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.processEntrenoTextEdit.setGeometry(QtCore.QRect(550, 140, 600, 300))
        self.processEntrenoTextEdit.setObjectName("processEntrenoTextEdit")


        self.MConfusionPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.MConfusionPushButton.setGeometry(QtCore.QRect(550, 480, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MConfusionPushButton.setFont(font)
        self.MConfusionPushButton.setObjectName("MConfusionPushButton")
        
        KNN.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(KNN)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 17)) 
        self.menubar.setObjectName("menubar")
        KNN.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(KNN)
        self.statusbar.setObjectName("statusbar")
        KNN.setStatusBar(self.statusbar)

        self.retranslateUi(KNN)
        QtCore.QMetaObject.connectSlotsByName(KNN)

    def retranslateUi(self, KNN):
        _translate = QtCore.QCoreApplication.translate
        KNN.setWindowTitle(_translate("KNN", "Configurar algortimo KNN"))
        self.titulo_2.setText(_translate("KNN", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; text-decoration: underline;\">K - Vecinos más cercanos</span></p></body></html>"))
        self.titulo2Label.setText(_translate("KNN", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Configuración</span></p></body></html>"))
        self.label1.setText(_translate("KNN", "Tamaño del conjunto de entrenamiento (%): "))
        self.label_2.setText(_translate("KNN", "Train:"))
        self.label_4.setText(_translate("KNN", "Test:"))
        self.kVecinos_label5.setText(_translate("KNN", "<b>Nº Vecinos (K):</b>"))
        self.setSizePushButton.setText(_translate("KNN", "Set"))
        self.weight_label_6.setText(_translate("KNN", "<b>Weight:</b>"))
        self.WeightComboBox.setItemText(0, _translate("KNN", "uniform"))
        self.WeightComboBox.setItemText(1, _translate("KNN", "distance"))
        self.algoritmo_label_7.setText(_translate("KNN", "<b>Algoritmo:</b>"))
        self.algoritmoComboBox.setItemText(0, _translate("KNN", "auto"))
        self.algoritmoComboBox.setItemText(1, _translate("KNN", "ball_tree"))
        self.algoritmoComboBox.setItemText(2, _translate("KNN", "kd_tree"))
        self.algoritmoComboBox.setItemText(3, _translate("KNN", "brute"))
        self.metrica_label_8.setText(_translate("KNN", "<b>Métrica: \'minkowski\'</b>"))
        self.p_label_9.setText(_translate("KNN", "<b>p:</b>"))
        self.pComboBox.setItemText(0, _translate("KNN", "euclidean_distance (p=2)"))
        self.pComboBox.setItemText(1, _translate("KNN", "manhattan_distance (p=1)"))
        self.EntrenarPushButton.setText(_translate("KNN", "Entrenar"))
        self.label_9.setText(_translate("KNN", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Entrenamiento de modelo</span></p></body></html>"))
        self.descargaPushButton.setText(_translate("KNN", "Descargar"))
        self.MConfusionPushButton.setText(_translate("KNN", "Gráficas"))
       


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KNN = QtWidgets.QMainWindow()
    ui = Ui_KNN()
    ui.setupUi(KNN)
    KNN.show()
    sys.exit(app.exec_())
