from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)  
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.TituloLabel = QtWidgets.QLabel(self.centralwidget)
        self.TituloLabel.setGeometry(QtCore.QRect(30, 20, 1140, 40))  
        self.TituloLabel.setTextFormat(QtCore.Qt.AutoText)
        self.TituloLabel.setObjectName("TituloLabel")

        self.selectDatasetPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.selectDatasetPushButton.setGeometry(QtCore.QRect(30, 90, 170, 40))  
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectDatasetPushButton.setFont(font)
        self.selectDatasetPushButton.setObjectName("selectDatasetPushButton")

        self.datasetTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.datasetTableWidget.setGeometry(QtCore.QRect(30, 150, 1140, 400))  
        self.datasetTableWidget.setObjectName("datasetTableWidget")
        self.datasetTableWidget.setColumnCount(0)
        self.datasetTableWidget.setRowCount(0)

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 560, 1140, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.filasLabel = QtWidgets.QLabel(self.centralwidget)
        self.filasLabel.setGeometry(QtCore.QRect(30, 590, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)  
        self.filasLabel.setFont(font)
        self.filasLabel.setLineWidth(1)
        self.filasLabel.setObjectName("filasLabel")

        self.filasValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.filasValueLabel.setGeometry(QtCore.QRect(90, 590, 80, 30)) 
        font = QtGui.QFont()
        font.setPointSize(10)  
        self.filasValueLabel.setFont(font)
        self.filasValueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filasValueLabel.setText("")
        self.filasValueLabel.setObjectName("filasValueLabel")

        self.columnasLabel = QtWidgets.QLabel(self.centralwidget)
        self.columnasLabel.setGeometry(QtCore.QRect(220, 590, 120, 30)) 
        font = QtGui.QFont()
        font.setPointSize(10)  
        self.columnasLabel.setFont(font)
        self.columnasLabel.setObjectName("columnasLabel")

        self.columnasValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.columnasValueLabel.setGeometry(QtCore.QRect(310, 590, 80, 30)) 
        font = QtGui.QFont()
        font.setPointSize(10)
        self.columnasValueLabel.setFont(font)
        self.columnasValueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.columnasValueLabel.setText("")
        self.columnasValueLabel.setObjectName("columnasValueLabel")

        self.Label = QtWidgets.QLabel(self.centralwidget)
        self.Label.setGeometry(QtCore.QRect(30, 650, 1140, 30))  
        font = QtGui.QFont()
        font.setPointSize(10)  
        self.Label.setFont(font)
        self.Label.setObjectName("Label")

        self.NNPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.NNPushButton.setGeometry(QtCore.QRect(30, 700, 150, 40))  
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NNPushButton.setFont(font)
        self.NNPushButton.setObjectName("NNPushButton")

        self.KNNPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.KNNPushButton.setGeometry(QtCore.QRect(200, 700, 150, 40))  
        font = QtGui.QFont()
        font.setPointSize(10)
        self.KNNPushButton.setFont(font)
        self.KNNPushButton.setObjectName("KNNPushButton")
        
        self.DTPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.DTPushButton.setGeometry(QtCore.QRect(370, 700, 150, 40)) 
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DTPushButton.setFont(font)
        self.DTPushButton.setObjectName("DTPushButton")

        self.SVCPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.SVCPushButton.setGeometry(QtCore.QRect(540, 700, 150, 40)) 
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SVCPushButton.setFont(font)
        self.SVCPushButton.setObjectName("SVCPushButton") 
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aplicación de Machine Learning"))
        self.TituloLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; text-decoration: underline;\">Importación del dataset y selección del modelo de entrenamiento.</span></p><p><br/></p></body></html>"))
        self.selectDatasetPushButton.setText(_translate("MainWindow", "Importar Dataset"))
        self.filasLabel.setText(_translate("MainWindow", "Nº Filas: "))
        self.columnasLabel.setText(_translate("MainWindow", "Nº Columnas: "))
        self.Label.setText(_translate("MainWindow", "Selecciona el modelo de entrenamiento"))
        self.NNPushButton.setText(_translate("MainWindow", "Red Neuronal"))
        self.DTPushButton.setText(_translate("MainWindow", "Decision Tree"))
        self.KNNPushButton.setText(_translate("MainWindow", "K-NN"))
        self.SVCPushButton.setText(_translate("MainWindow", "SVM")) 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
