from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NNWindow(object):
    def setupUi(self, NNWindow):
        NNWindow.setObjectName("NNWindow")
        NNWindow.resize(1200, 800)  
        self.centralwidget = QtWidgets.QWidget(NNWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.titulo = QtWidgets.QLabel(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(40, 20, 900, 40))  
        font = QtGui.QFont()
        font.setPointSize(16)  
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")

        self.titulo2Label = QtWidgets.QLabel(self.centralwidget)
        self.titulo2Label.setGeometry(QtCore.QRect(40, 80, 900, 30)) 
        font = QtGui.QFont()
        font.setPointSize(12)
        self.titulo2Label.setFont(font)
        self.titulo2Label.setObjectName("titulo2Label")

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(40, 130, 400, 30)) 
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")

        self.sizeConjuntoLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sizeConjuntoLineEdit.setGeometry(QtCore.QRect(80, 170, 100, 30))  
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sizeConjuntoLineEdit.setFont(font)
        self.sizeConjuntoLineEdit.setObjectName("sizeConjuntoLineEdit")

        self.setSizePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.setSizePushButton.setGeometry(QtCore.QRect(190, 170, 100, 30))  
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setSizePushButton.setFont(font)
        self.setSizePushButton.setObjectName("setSizePushButton")

        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(40, 220, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")

        self.trainValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.trainValueLabel.setGeometry(QtCore.QRect(110, 220, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trainValueLabel.setFont(font)
        self.trainValueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trainValueLabel.setObjectName("trainValueLabel")

        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(200, 220, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")

        self.testValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.testValueLabel.setGeometry(QtCore.QRect(260, 220, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testValueLabel.setFont(font)
        self.testValueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.testValueLabel.setObjectName("testValueLabel")

        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(40, 270, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")

        self.capasLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.capasLineEdit.setGeometry(QtCore.QRect(240, 270, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.capasLineEdit.setFont(font)
        self.capasLineEdit.setObjectName("capasLineEdit")

        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setGeometry(QtCore.QRect(40, 320, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label6.setFont(font)
        self.label6.setObjectName("label6")

        self.optimizadorComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.optimizadorComboBox.setGeometry(QtCore.QRect(240, 320, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.optimizadorComboBox.setFont(font)
        self.optimizadorComboBox.setObjectName("optimizadorComboBox")
        self.optimizadorComboBox.addItem("")
        self.optimizadorComboBox.addItem("")
        
        self.batchLabel = QtWidgets.QLabel(self.centralwidget)
        self.batchLabel.setGeometry(QtCore.QRect(40, 370, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.batchLabel.setFont(font)
        self.batchLabel.setObjectName("batchLabel")

        self.batchSizeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.batchSizeComboBox.setGeometry(QtCore.QRect(240, 370, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.batchSizeComboBox.setFont(font)
        self.batchSizeComboBox.setObjectName("batchSizeComboBox")
        self.batchSizeComboBox.addItem("")
        self.batchSizeComboBox.addItem("")
        self.batchSizeComboBox.addItem("")
        self.batchSizeComboBox.addItem("")

        self.label7 = QtWidgets.QLabel(self.centralwidget)
        self.label7.setGeometry(QtCore.QRect(40, 420, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label7.setFont(font)
        self.label7.setObjectName("label7")

        self.epochsLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.epochsLineEdit.setGeometry(QtCore.QRect(240, 420, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.epochsLineEdit.setFont(font)
        self.epochsLineEdit.setObjectName("epochsLineEdit")

        self.crearModeloPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.crearModeloPushButton.setGeometry(QtCore.QRect(60, 470, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.crearModeloPushButton.setFont(font)
        self.crearModeloPushButton.setObjectName("crearModeloPushButton")

        self.EntrenarPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.EntrenarPushButton.setGeometry(QtCore.QRect(240, 470, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EntrenarPushButton.setFont(font)
        self.EntrenarPushButton.setObjectName("EntrenarPushButton")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(500, 60, 20, 600))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.processEntrenoTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.processEntrenoTextEdit.setGeometry(QtCore.QRect(550, 140, 600, 300))
        self.processEntrenoTextEdit.setObjectName("processEntrenoTextEdit")

        self.label9 = QtWidgets.QLabel(self.centralwidget)
        self.label9.setGeometry(QtCore.QRect(550, 80, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label9.setFont(font)
        self.label9.setObjectName("label9")

        self.MConfusionPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.MConfusionPushButton.setGeometry(QtCore.QRect(550, 480, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MConfusionPushButton.setFont(font)
        self.MConfusionPushButton.setObjectName("MConfusionPushButton")

        self.descargaPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.descargaPushButton.setGeometry(QtCore.QRect(1000, 480, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.descargaPushButton.setFont(font)
        self.descargaPushButton.setObjectName("descargaPushButton")

        NNWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(NNWindow)
        QtCore.QMetaObject.connectSlotsByName(NNWindow)

    def retranslateUi(self, NNWindow):
        _translate = QtCore.QCoreApplication.translate
        NNWindow.setWindowTitle(_translate("NNWindow", "Configurar Red Neuronal"))
        self.titulo.setText(_translate("NNWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; text-decoration: underline;\">Redes Neuronales</span></p></body></html>"))
        self.titulo2Label.setText(_translate("NNWindow", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Configuración</span></p></body></html>"))
        self.label1.setText(_translate("NNWindow", "Tamaño del conjunto de entrenamiento (%):"))
        self.setSizePushButton.setText(_translate("NNWindow", "Set"))
        self.label2.setText(_translate("NNWindow", "Train:"))
        self.label4.setText(_translate("NNWindow", "Test:"))
        self.label3.setText(_translate("NNWindow", "<b>Nº Capas:</b>"))
        self.label6.setText(_translate("NNWindow", "<b>Optimizador:</b>"))
        self.batchLabel.setText(_translate("NNWindow", "<b>Batch size:</b>"))
        self.label7.setText(_translate("NNWindow", "<b>Epochs:</b>"))
        self.optimizadorComboBox.setItemText(0, _translate("NNWindow", "adam"))
        self.optimizadorComboBox.setItemText(1, _translate("NNWindow", "sgd"))
        self.batchSizeComboBox.setItemText(0, _translate("NNWindow", "32"))
        self.batchSizeComboBox.setItemText(1, _translate("NNWindow", "64"))
        self.batchSizeComboBox.setItemText(2, _translate("NNWindow", "128"))
        self.batchSizeComboBox.setItemText(3, _translate("NNWindow", "256"))
        self.crearModeloPushButton.setText(_translate("NNWindow", "Crear Modelo"))
        self.EntrenarPushButton.setText(_translate("NNWindow", "Entrenar"))
        self.label9.setText(_translate("NNWindow", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Entrenamiento de modelo</span></p></body></html>"))
        self.descargaPushButton.setText(_translate("NNWindow", "Descargar"))
        self.MConfusionPushButton.setText(_translate("NNWindow", "Gráficas"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NNWindow = QtWidgets.QMainWindow()
    ui = Ui_NNWindow()
    ui.setupUi(NNWindow)
    NNWindow.show()
    sys.exit(app.exec_())
