from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SVC(object):
    def setupUi(self, SVC):
        SVC.setObjectName("SVC")
        SVC.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(SVC)
        self.centralwidget.setObjectName("centralwidget")

        self.titulo_2 = QtWidgets.QLabel(self.centralwidget)
        self.titulo_2.setGeometry(QtCore.QRect(40, 20, 900, 40))  
        font = QtGui.QFont()
        font.setPointSize(16) 
        self.titulo_2.setFont(font)
        self.titulo_2.setObjectName("titulo_2")

        self.descargaPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.descargaPushButton.setGeometry(QtCore.QRect(1000, 480, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.descargaPushButton.setFont(font)
        self.descargaPushButton.setObjectName("descargaPushButton")

        self.setSizePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.setSizePushButton.setGeometry(QtCore.QRect(190, 170, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.setSizePushButton.setFont(font)
        self.setSizePushButton.setObjectName("setSizePushButton")

        self.sizeConjuntoLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sizeConjuntoLineEdit.setGeometry(QtCore.QRect(80, 170, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sizeConjuntoLineEdit.setFont(font)
        self.sizeConjuntoLineEdit.setObjectName("sizeConjuntoLineEdit")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 220, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.penalizacionC_label5 = QtWidgets.QLabel(self.centralwidget)
        self.penalizacionC_label5.setGeometry(QtCore.QRect(40, 270, 900, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.penalizacionC_label5.setFont(font)
        self.penalizacionC_label5.setObjectName("penalizacionC_label5")

        self.penalizacionC_label6 = QtWidgets.QLabel(self.centralwidget)
        self.penalizacionC_label6.setGeometry(QtCore.QRect(40, 290, 900, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.penalizacionC_label6.setFont(font)
        self.penalizacionC_label6.setObjectName("penalizacionC_label6")

        self.titulo2Label = QtWidgets.QLabel(self.centralwidget)
        self.titulo2Label.setGeometry(QtCore.QRect(40, 80, 900, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.titulo2Label.setFont(font)
        self.titulo2Label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titulo2Label.setObjectName("titulo2Label")
        
        self.trainValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.trainValueLabel.setGeometry(QtCore.QRect(110, 220, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trainValueLabel.setFont(font)
        self.trainValueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.trainValueLabel.setText("")
        self.trainValueLabel.setObjectName("trainValueLabel")
        
        self.testValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.testValueLabel.setGeometry(QtCore.QRect(260, 220, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.testValueLabel.setFont(font)
        self.testValueLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.testValueLabel.setText("")
        self.testValueLabel.setObjectName("testValueLabel")

        self.kernel_label_6 = QtWidgets.QLabel(self.centralwidget)
        self.kernel_label_6.setGeometry(QtCore.QRect(40, 330, 900, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kernel_label_6.setFont(font)
        self.kernel_label_6.setObjectName("kernel_label_6")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 80, 400, 30))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setObjectName("label_9")

        self.EntrenarPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.EntrenarPushButton.setGeometry(QtCore.QRect(240, 400, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.EntrenarPushButton.setFont(font)
        self.EntrenarPushButton.setObjectName("EntrenarPushButton")

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(40, 130, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")

        self.penalizacionCLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.penalizacionCLineEdit.setGeometry(QtCore.QRect(290, 270, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.penalizacionCLineEdit.setFont(font)
        self.penalizacionCLineEdit.setObjectName("penalizacionCLineEdit")
        
        self.processEntrenoTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.processEntrenoTextEdit.setGeometry(QtCore.QRect(550, 140, 600, 300))
        self.processEntrenoTextEdit.setObjectName("processEntrenoTextEdit")

        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(500, 60, 20, 600))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 220, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.MConfusionPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.MConfusionPushButton.setGeometry(QtCore.QRect(550, 480, 150, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MConfusionPushButton.setFont(font)
        self.MConfusionPushButton.setObjectName("MConfusionPushButton")

        self.KernelComboBox2 = QtWidgets.QComboBox(self.centralwidget)
        self.KernelComboBox2.setGeometry(QtCore.QRect(290, 330, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.KernelComboBox2.setFont(font)
        self.KernelComboBox2.setObjectName("KernelComboBox2")
        self.KernelComboBox2.addItem("")
        self.KernelComboBox2.addItem("")
        self.KernelComboBox2.addItem("")
        self.KernelComboBox2.addItem("")

        SVC.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SVC)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 17))
        self.menubar.setObjectName("menubar")
        SVC.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SVC)
        self.statusbar.setObjectName("statusbar")
        SVC.setStatusBar(self.statusbar)

        self.retranslateUi(SVC)
        QtCore.QMetaObject.connectSlotsByName(SVC)

    def retranslateUi(self, SVC):
        _translate = QtCore.QCoreApplication.translate
        SVC.setWindowTitle(_translate("SVC", "Configurar SVM"))
        self.descargaPushButton.setText(_translate("SVC", "Descargar"))
        self.setSizePushButton.setText(_translate("SVC", "Set"))
        self.label_2.setText(_translate("SVC", "Train:"))
        self.penalizacionC_label5.setText(_translate("SVC", "<b>Parámetro de penalización (C):</b>"))
        self.penalizacionC_label6.setText(_translate("SVC", "(Por defecto = 1.0)"))
        self.titulo2Label.setText(_translate("SVC", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Configuración</span></p></body></html>"))
        self.kernel_label_6.setText(_translate("SVC", "<b>Kernel:</b>"))
        self.label_9.setText(_translate("SVC", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline;\">Entrenamiento de modelo</span></p></body></html>"))
        self.EntrenarPushButton.setText(_translate("SVC", "Entrenar"))
        self.label1.setText(_translate("SVC", "Tamaño del conjunto de entrenamiento (%): "))
        self.titulo_2.setText(_translate("SVC", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700;\">Máquinas de Vectores de Soporte</span></p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("SVC", "Test:"))
        self.MConfusionPushButton.setText(_translate("SVC", "Gráficas"))
        self.KernelComboBox2.setItemText(0, _translate("SVC", "rbf"))
        self.KernelComboBox2.setItemText(1, _translate("SVC", "linear"))
        self.KernelComboBox2.setItemText(2, _translate("SVC", "poly"))
        self.KernelComboBox2.setItemText(3, _translate("SVC", "sigmoid"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SVC = QtWidgets.QMainWindow()
    ui = Ui_SVC()
    ui.setupUi(SVC)
    SVC.show()
    sys.exit(app.exec_())
